# Generated by Django 4.2.3 on 2023-07-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='narxi',
        ),
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
