# Generated by Django 4.2.3 on 2023-07-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_blog_home_servis_alter_project_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
