# Generated by Django 4.2.3 on 2023-07-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_delete_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rasm',
            field=models.ImageField(default=2, upload_to='media'),
            preserve_default=False,
        ),
    ]
