# Generated by Django 4.2.3 on 2023-08-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_blog_rasm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servis',
        ),
    ]
